import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import axios from "axios";
import { toast } from "react-toastify";
import { FiEye, FiEyeOff, FiMail, FiLock, FiUser } from "react-icons/fi";
import AuthShell from "../components/AuthShell";
const AUTH_API = import.meta.env.VITE_AUTH_API_URL || "http://localhost:5000/api/auth";

export default function SignUp() {
  const [form,setForm]=useState({fullName:"",email:"",password:"",confirmPassword:""}); const [show,setShow]=useState(false); const [loading,setLoading]=useState(false); const navigate=useNavigate(); const change=e=>setForm({...form,[e.target.name]:e.target.value});
  const submit=async e=>{e.preventDefault(); if(form.password!==form.confirmPassword)return toast.error("Passwords do not match"); setLoading(true); try{await axios.post(`${AUTH_API}/register`,form);localStorage.setItem("lokniti_pending_email",form.email);toast.success("Verification code sent");navigate("/verify-otp",{state:{email:form.email}})}catch(err){toast.error(err.response?.data?.message||"Unable to create account")}finally{setLoading(false)}};
  return <AuthShell eyebrow="CREATE YOUR ACCOUNT" title="Start researching smarter" text="Set up your free Lokniti workspace in a minute."><form className="auth-form" onSubmit={submit}><label>Full name<div className="field"><FiUser/><input name="fullName" placeholder="Your full name" minLength="2" required value={form.fullName} onChange={change}/></div></label><label>Email address<div className="field"><FiMail/><input name="email" type="email" placeholder="you@example.com" required value={form.email} onChange={change}/></div></label><div className="two-fields"><label>Password<div className="field"><FiLock/><input name="password" type={show?"text":"password"} placeholder="Min. 6 characters" minLength="6" required value={form.password} onChange={change}/><button type="button" onClick={()=>setShow(!show)}>{show?<FiEyeOff/>:<FiEye/>}</button></div></label><label>Confirm password<div className="field"><FiLock/><input name="confirmPassword" type={show?"text":"password"} placeholder="Repeat password" minLength="6" required value={form.confirmPassword} onChange={change}/></div></label></div><label className="checkbox terms"><input type="checkbox" required/> I agree to the Terms of Service and Privacy Policy.</label><button className="button button--primary submit-button" disabled={loading}>{loading?<><i className="spinner"/> Creating account…</>:"Create free account"}</button></form><p className="auth-switch">Already have an account? <Link to="/login">Sign in</Link></p></AuthShell>;
}
